-- DATABASE_NAMEを実際のテーブル名に置き換えてください
-- 例: oc1220

-- 1. テーブルの作成
create table public.DATABASE_NAME (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  path_data jsonb, -- お絵描きの座標データ（JSON形式）
  width integer,   -- キャンバスの幅
  height integer   -- キャンバスの高さ
);

-- 2. 権限設定（RLS: Row Level Security）
-- イベント用なので、認証なし(anon)で「誰でも書き込み・読み込み可能」にします
alter table public.DATABASE_NAME enable row level security;

create policy "Enable read/write for everyone"
on public.DATABASE_NAME
for all
using (true)
with check (true);

-- 3. リアルタイム機能の有効化（重要！）
-- これがないと、Display.svelte側でリアルタイムに絵が表示されません
alter publication supabase_realtime add table public.DATABASE_NAME;

-- 完了メッセージ（実行結果確認用）
select 'Setup Complete!' as status;